import { useState } from 'react';
import { ArrowRight, CheckCircle2, Lock, Mail, Mic, ShoppingCart, Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/useAuthStore';

export default function Landing(){
 const nav=useNavigate(); const login=useAuthStore(s=>s.login); const register=useAuthStore(s=>s.register); const google=useAuthStore(s=>s.google); const guest=useAuthStore(s=>s.guest); const loading=useAuthStore(s=>s.loading); const error=useAuthStore(s=>s.error); const [email,setEmail]=useState(''); const [pass,setPass]=useState(''); const [name,setName]=useState(''); const [signup,setSignup]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault(); try{ if(signup) await register(email,pass,name); else await login(email,pass); nav('/home'); }catch{}};
 const googleLogin=async()=>{try{await google();nav('/home')}catch{}};
 return <div className="login-page"><section className="login-hero"><div className="login-hero-copy"><div className="login-brand"><ShoppingCart size={23}/>VoiceCart AI</div><span className="login-kicker"><Sparkles size={14}/>THE SMARTER WAY TO SHOP</span><h1>Your groceries.<br/><em>Just say the word.</em></h1><p>Search, build a complete cart and shop naturally in English, Hindi or Hinglish—all in one flow.</p><div className="login-points"><span><CheckCircle2/>One-tap voice shopping</span><span><CheckCircle2/>Multi-product orders</span><span><CheckCircle2/>Personal recommendations</span></div><button type="button" className="login-hero-demo" onClick={()=>document.getElementById('login-form')?.scrollIntoView({behavior:'smooth'})}>Start shopping <ArrowRight size={16}/></button></div><div className="login-hero-image"><img src="/assets/login-hero.png" alt="Voice-powered grocery shopping"/><div className="floating-voice"><Mic size={20}/><span>Speak naturally</span></div></div></section><section className="login-panel"><form id="login-form" onSubmit={submit} className="login-card"><div className="login-card-head"><div className="login-mobile-logo"><ShoppingCart size={21}/></div><h2>{signup?'Create your account':'Welcome back'}</h2><p>{signup?'Save your profile, orders and recommendations securely.':'Sign in to continue your VoiceCart journey.'}</p></div>{signup&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required/></label>}<label>Email<div className="input-wrap"><Mail size={18}/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email" required/></div></label><label>Password<div className="input-wrap"><Lock size={18}/><input value={pass} onChange={e=>setPass(e.target.value)} placeholder="Minimum 6 characters" type="password" minLength={6} required/></div></label>{error&&<p className="auth-error">{error}</p>}<button disabled={loading} className="btn btn-primary login-submit">{loading?'Please wait…':signup?'Create Account':'Log In'}</button><div className="login-divider"><span/>or<span/></div><button type="button" disabled={loading} onClick={googleLogin} className="google-button"><span className="google-g">G</span>Continue with Google</button><button type="button" className="auth-switch" onClick={()=>setSignup(v=>!v)}>{signup?'Already have an account? Log in':'New to VoiceCart AI? Create an account'}</button><button type="button" onClick={()=>{guest();nav('/home')}} className="guest-button">Continue as Guest</button></form></section></div>
}
