import { useCallback, useState } from 'react';
import { NLPResult, Product } from '../types';
import { useCartStore } from '../store/useCartStore';
import { useProductStore } from '../store/useProductStore';
import { resolveIngredientsForDish } from '../utils/recipeResolver';
import { useNavigate } from 'react-router-dom';
import { speak } from '../utils/speech';
export type ToastType='success'|'error'|'info'|'substitutes'; export interface Toast{id:string;message:string;type:ToastType;substitutes?:Product[]}
export function useCommandExecutor(){ const navigate=useNavigate(); const [toasts,setToasts]=useState<Toast[]>([]); const addToast=useCallback((t:Omit<Toast,'id'>,talk=true)=>{const id=crypto.randomUUID?.()||Math.random().toString(36);setToasts(x=>[...x,{...t,id}]);setTimeout(()=>setToasts(x=>x.filter(a=>a.id!==id)),4500);if(talk)speak(t.message.replace(/₹/g,'rupees '));},[]); const dismissToast=(id:string)=>setToasts(x=>x.filter(t=>t.id!==id));
 const execute=useCallback((r:NLPResult)=>{const ps=useProductStore.getState(); const cart=useCartStore.getState(); const products=ps.products; const find=(key:string)=>{const q=key.toLowerCase().trim();return products.find(p=>p.id===q||p.name.toLowerCase().includes(q)||q.includes(p.name.toLowerCase())||p.tags.some(t=>q.includes(t.toLowerCase())||t.toLowerCase().includes(q))||p.productType?.toLowerCase()===q)}; const product=r.product?find(r.product):undefined;
 switch(r.intent){case'MULTI_ADD':{const added:string[]=[];const missing:string[]=[];(r.items||[]).forEach(item=>{const p=find(item.product);if(p&&p.available){cart.addItem(p,item.quantity||1);added.push(`${item.quantity||1} ${p.name}`)}else missing.push(item.product)});let message=added.length?`Added ${added.join(', ')} to your cart.`:'I could not find the requested products.';if(missing.length)message+=` I could not find: ${missing.join(', ')}.`;addToast({message,type:added.length?'success':'error'});break;}case'ADD_ITEM': if(!product){addToast({message:"I couldn't find that product. Try the product name or search for it.",type:'error'});break;} const qty=r.quantity||1; const total=cart.items.reduce((s,i)=>s+(products.find(p=>p.id===i.productId)?.price||0)*i.quantity,0)+product.price*qty; cart.addItem(product,qty); if(cart.budget!==null&&total>cart.budget)addToast({message:`Added ${product.name}. Warning: you are ₹${Math.round(total-cart.budget)} over budget.`,type:'error'}); else addToast({message:`Added ${qty} ${r.unit||product.unit}${qty>1?'s':''} of ${product.name}.`,type:'success'});break;
 case'REMOVE_ITEM': if(!product){addToast({message:"I couldn't identify what to remove.",type:'error'});break;} cart.removeItem(product.id);addToast({message:`Removed ${product.name}.`,type:'success'});break;
 case'UPDATE_QUANTITY':if(!product||!r.quantity){addToast({message:'Specify a product and quantity.',type:'error'});break;}cart.updateQuantity(product.id,r.quantity);addToast({message:`Updated ${product.name} to ${r.quantity}.`,type:'success'});break;
 case'SEARCH_PRODUCT':case'FILTER_PRODUCTS':ps.setSearchQuery(r.product||'');navigate(`/products?search=${encodeURIComponent(r.product||'')}`);addToast({message:'Showing matching products.',type:'info'});break;
 case'GET_SUBSTITUTES':if(!product){addToast({message:'Tell me which product you want to replace.',type:'error'});break;}const subs=ps.getSubstitutes(product.id);addToast({message:subs.length?`Here are alternatives to ${product.name}.`:`No same-type alternatives found for ${product.name}.`,type:subs.length?'substitutes':'info',substitutes:subs});break;
 case'SHOW_LIST':navigate('/cart');break; case'CLEAR_LIST':cart.clearCart();addToast({message:'Shopping list cleared.',type:'success'});break;
 case'SET_BUDGET':if(r.budgetAmount===undefined){addToast({message:'Please specify a budget amount.',type:'error'});break;}cart.setBudget(r.budgetAmount);addToast({message:`Budget set to ₹${r.budgetAmount}.`,type:'success'});break;
 case'OPTIMIZE_CART':const o=cart.optimizeCart();addToast({message:o.swaps.length?`Cart optimized. You saved ₹${Math.round(o.totalSaved)}.`:'Your cart is already optimized.',type:o.swaps.length?'success':'info'});if(o.swaps.length)navigate('/cart');break;
 case'COOK_RECIPE':const dish=r.recipeName||'pancakes';const ingredients=resolveIngredientsForDish(dish,products);if(!ingredients.length){addToast({message:`I couldn't resolve ingredients for ${dish}.`,type:'error'});break;}ingredients.forEach(i=>cart.addItem(i.product,i.quantity));addToast({message:`Added ingredients for ${dish}.`,type:'success'});navigate('/cart');break;
 case'PROCEED_CHECKOUT':navigate('/checkout');break;case'CONFIRM_PAYMENT':navigate('/history');addToast({message:'Payment confirmed for the demo order.',type:'success'});break;default:addToast({message:'Try saying Add milk, Find apples under 100, or Optimize my cart.',type:'info'});}},[navigate,addToast]); return{execute,toasts,dismissToast,addToast}; }
